Add publishing to CocoaPods for iOS
instrumentisto/libwebrtc-bin pull request #15
Opened 2022-10-28 10:02 UTC by evdokimovs

## Synopsis

This PR adds releasing of iOS library to the CocoaPods.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-10-28 10:41 UTC, evdokimovs commented
## FCM

```
Add publishing to CocoaPods for iOS (#15)
```

2022-10-31 16:00 UTC, tyranron requested changes

2022-10-31 16:00 UTC, tyranron commented on scripts/generate_podspec.sh
> +    spec.vendored_frameworks = "WebRTC.xcframework"
@evdokimovs having the full spec declared twice (in the script and in the generated file) is just not DRY.

Could we just replace the version in `.pospec` like we do for the `VERSION` file? We could even use the same `upgrade-ver.sh` script for that. No need in a separate one.

2022-10-31 16:04 UTC, tyranron commented
@evdokimovs and we may also add a badge to README with CocoaPods version, like we do for JitPack.

2022-11-01 12:41 UTC, tyranron approved these changes

2022-11-01 14:43 UTC, merged