Add schedule `Chrome` weekly check
instrumentisto/libwebrtc-bin pull request #5
Opened 2022-07-07 11:10 UTC by logist322

## Synopsis

This PR adds a new schedule workflow for checking the last stable version of the Chrome and creates a new automate PR with updated `version` and `commit`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-07-07 11:12 UTC, logist322 commented
## FCM
```
Add schedule `Chrome` weekly check (#5)
```

2022-07-14 05:56 UTC, alexlapa approved these changes

2022-07-14 13:17 UTC, tyranron commented on .github/workflows/chrome-check.yml
> +          commit-message: Upgrade to ${{ env.LAST_VERSION }} version
@logist322 do we have idempotency here? If the branch already exists, will this step succeed, or fail, or create a new PR?

2022-07-14 14:43 UTC, logist322 commented on .github/workflows/chrome-check.yml
> +            exit 1
@tyranron got it!

2022-07-14 15:44 UTC, tyranron commented on .github/workflows/chrome-check.yml
> +          commit-message: Upgrade to ${{ env.LAST_VERSION }} version
@logist322 no, I think the default behavior is idempotent enough.

2022-07-15 16:02 UTC, logist322 commented
@alexlapa review ping.

2022-07-22 10:00 UTC, tyranron requested changes

2022-07-24 16:08 UTC, tyranron approved these changes

2022-07-24 16:08 UTC, tyranron commented on upgrade-ver.sh
> +        sed -i "${line}s|.*|${field}=${value}|g" ./VERSION
@logist322 implementation is unnecessarily complicated.

2022-07-25 10:39 UTC, merged